### PR TITLE
protocol containing zero & CGPoint extension

### PR DESCRIPTION
**Pull request by ashleymills**

### CODE REVIEW

**Comment by practicalswift** [comment]
@ashleymills Are you able to reproduce using `swiftc` compiled from current `master` running under Linux? :-)

**Comment by ashleymills** [comment]
No - this is under Xcode 8.3.1 on macOS

**Comment by practicalswift** [comment]
@ashleymills It is not stated explicitly, but I'm running `swiftc` compiled from current `master` under Linux and I must be able reproduce the crashes.

If this is macOS only and crashing `swiftc` compiled from current `master` - please consider filing a Radar.

Thanks for reporting anyways!

**Comment by practicalswift** [comment]
I'll close this for now, but let me know if you're able to reproduce under Linux and I'll re-open :-)  Thanks for reporting!

**Pull request closed without merging**
