### PR TITLE
Move 23898 23899 To /fixed

### PR DESCRIPTION
**Pull request by CodaFi**
Per the discussion in #52

### CODE REVIEW

**Comment by beltex** [comment]
Looks like the test numbers need to be updated as the following already exist

```
23898-swift-silfunction-maptypeintocontext.swift
23899-segfault.swift
```

The next one up should now be **24892**

**Comment by CodaFi** [comment]
Weird.  Renumbered.

**Comment by practicalswift** [comment]
Thanks for contributing @CodaFi and @beltex :-)

**Comment by beltex** [comment]
np! :)

**Pull request merged**
