### PR TITLE
DeclName::print causes seg fault 11 in this case

### PR DESCRIPTION
**Pull request by zoren**

### CODE REVIEW

**Comment by practicalswift** [comment]
@zoren Thanks for the contribution! I'm changing the license for all new contributions to the following: "Licensed under Apache License v2.0 with Runtime Library Exception".

Are you okay with that license for this contribution? :-)

**Comment by zoren** [comment]
Yes I'm definitely ok with that! And thank you for your contributions!

**Comment by practicalswift** [comment]
@zoren After some testing it seems like this crash case doesn't crash `swiftc` compiled from current `master`. Please don't hesitate to re-open if you believe I'm mistaken :-)

**Comment by zoren** [comment]
I think you're right, it's only in 2.2. Sorry.

**Pull request closed without merging**
