### PR TITLE
Large array and dictionary literals

### PR DESCRIPTION
**Pull request by neilpa**
Dictionary literals with more than 1300 entries and array literals with more than 2600 values segfault the compiler.

### CODE REVIEW

**Comment by practicalswift** [comment]
Hi @neilpa - thanks the contribution. This bug does not seem to affect the latest Xcode release; Apple Swift version 1.2 (swiftlang-602.0.42.4 clang-602.0.42)

Could you test those two cases under the latest Xcode release as well?

**Comment by neilpa** [comment]
@practicalswift I think that's the version of Swift which shipped with Xcode 6.3 beta 2. I've updated to beta 3 and that's where I'm seeing these crashes.

```
> swiftc --version
Apple Swift version 1.2 (swiftlang-602.0.44.6 clang-602.0.45)
Target: x86_64-apple-darwin14.1.0
> xcodebuild -version
Xcode 6.3
Build version 6D543q
```

**Comment by beltex** [comment]
Indeed, passes on **Xcode 6.3 beta 2**, but segfaults on **Xcode 6.3 beta 3**.

```bash
# Xcode 6.3 beta 2
$ xcodebuild -version
Xcode 6.3
Build version 6D532l
$ xcrun swiftc -v
Apple Swift version 1.2 (swiftlang-602.0.42.4 clang-602.0.42)
Target: x86_64-apple-darwin14.1.0
$ xcrun swiftc 24796-no-stacktrace.swift 
$ xcrun swiftc 24797-no-stacktrace.swift

# Xcode 6.3 beta 3
xcodebuild -version
Xcode 6.3
Build version 6D543q
$ xcrun swiftc -v
Apple Swift version 1.2 (swiftlang-602.0.44.6 clang-602.0.45)
Target: x86_64-apple-darwin14.1.0
$ xcrun swiftc 24796-no-stacktrace.swift 
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: swift frontend command failed due to signal (use -v to see invocation)
$ xcrun swiftc 24797-no-stacktrace.swift 
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: swift frontend command failed due to signal (use -v to see invocation)
```

**Comment by practicalswift** [comment]
@neilpa + @beltex - sorry, my bad – I was testing with the wrong Xcode version. I've now merged those those tests. Thanks a lot for contributing! :-)

**Pull request merged**
