### PR TITLE
23898-23899: Crashes with inout Parameters in Closures

### PR DESCRIPTION
**Pull request by CodaFi**
Prior art for these can be found [here](http://stackoverflow.com/questions/26746913/inout-parameter-in-closure-crashes-the-swift-compiler).

### CODE REVIEW

**Comment by practicalswift** [comment]
Those two have been fixed now in the latest beta. Thanks for reporting and sorry for not checking in on them earlier :-)

**Comment by beltex** [comment]
Forgot to say this months ago :)

Was just wondering, since these caused crashes before, shouldn’t they be added for the purpose of catching regressions?

**Comment by practicalswift** [comment]
Yes, you're correct. Please feel free to add them to the crashes-fixed/ directory :-)

**Comment by practicalswift** [comment]
@beltex

**Comment by beltex** [comment]
@practicalswift Sure thing!

@CodaFi Would you like me to create a new pull request or will you reopen this?

**Comment by CodaFi** [comment]
@beltex I'd be happy to create a new pull request.  Give me a few minutes to get everything setup.

**Comment by beltex** [comment]
@CodaFi Great, thanks!

**Pull request closed without merging**
